# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Rahul Raj R
title: Bachelor's in Computer Application
email: rahulraj_2001@hotmail.com
# email_title: Email (Email title override)
phone: 9148520218
# phone_title: Phone (Phone title override)

# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links



facebook_username: "https://www.facebook.com/profile.php?id=100004057374960"
instagram_username: "https://www.instagram.com/_rahul_raj_r/"
about_profile_image: images/WhatsApp Image 2022-06-11 at 2.49.18 PM.jpeg
about_content: | # this will include new lines to allow paragraphs
  I am fluent in 3 Languages which is English, Hindi and Kannada . I graduated from Widia Poorna Prajna School with a 72% grade point average. I completed my pre-university college in Vidya Soudha PU college with a First prize in Science fare for performing ethical hacking and graduated my college with an 82% and completed my Bachelors degree in Computer Applications in Jain Deemed to be University.  

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: NFT Marketplace with Asset Authenticity Verification
        link: https://drive.google.com/file/d/1GDOy4L4_N6xaHjKGYqPpS7O_ydT3aLon/view?usp=sharing
        link_text: Reaserch Paper
        additional_links:
          
        quote: >
          Short overview of the project
        description: Non-fungible Tokens (NFTs) are a sort of virtual crypto asset and money that are produced utilizing blockchain technology. In recent years, the popularity of blockchain technology, as well as dealing in crypto assets, has risen. Having said that, as seen in recent years, the NFT market is also booming. The idea of NFT is built on an Ethereum token standard that tries to identify and differentiate each token by attaching its unique signature to digital assets.
          
          This project proposes to improve the security characteristics of the NFT Marketplace. It attempts to accomplish this by presenting the technique of Asset Verification in order to secure NFTs from getting into incorrect hands and avoid misuse. Asset Verification is performed by issuing a unique alphanumeric key to each NFT that the seller desires to sell. This offers legitimacy to the NFT and helps to combat piracy. It also allows users an interface to generate, purchase and sell NFTs in this marketplace.
         
  - title: Bachelor's in Computer Application
    layout: list
    content:
      - layout: top-right
        title: Jain deemed to Be university
        sub_title: Bachelor's in Computer Application
        caption: 2019 -2022
        quote: >
          
  - title: A Little More About Me
    layout: text
    content: Love Swimming and Gardening
      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
